; March7th_Weapon

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideMarch7th_WeaponPosition]
hash = 87ddba61
handling = skip
vb0 = ResourceMarch7th_WeaponPosition
vb2 = ResourceMarch7th_WeaponBlend
draw = 2814,0

[TextureOverrideMarch7th_WeaponTexcoord]
hash = 0c477159
vb1 = ResourceMarch7th_WeaponTexcoord

[TextureOverrideMarch7th_WeaponVertexLimitRaise]
hash = 18e79418

[TextureOverrideMarch7th_WeaponIB]
hash = b853a162
handling = skip
drawindexed = auto

[TextureOverrideMarch7th_WeaponA]
hash = b853a162
match_first_index = 0
ib = ResourceMarch7th_WeaponAIB

[TextureOverrideMarch7th_WeaponADiffuse]
hash = 52e8727a
this = ResourceMarch7th_WeaponADiffuse

[TextureOverrideMarch7th_WeaponALightMap]
hash = f47e4ed8
this = ResourceMarch7th_WeaponALightMap

; CommandList -----------------------

; Resources -------------------------

[ResourceMarch7th_WeaponPosition]
type = Buffer
stride = 40
filename = March7th_WeaponPosition.buf

[ResourceMarch7th_WeaponBlend]
type = Buffer
stride = 16
filename = March7th_WeaponBlend.buf

[ResourceMarch7th_WeaponTexcoord]
type = Buffer
stride = 8
filename = March7th_WeaponTexcoord.buf

[ResourceMarch7th_WeaponAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = March7th_WeaponA.ib

[ResourceMarch7th_WeaponADiffuse]
filename = March7th_WeaponADiffuse.dds

[ResourceMarch7th_WeaponALightMap]
filename = March7th_WeaponALightMap.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord