; Merged Mod: .\0 - Dress\TravelerGirlMod\TravelerGirl.ini, .\1 - Dress no Top\TravelerGirlMod\TravelerGirl.ini, .\2 - No Dress no Top\TravelerGirlMod\TravelerGirl.ini, .\3 - No Dress\TravelerGirlMod\TravelerGirl.ini

; Constants ---------------------------

[Constants]
global persist $swapvar = 0
global $active
global $creditinfo = 0

[KeySwap]
condition = $active == 1
key = ;
back = '
type = cycle
$swapvar = 0,1,2,3
$creditinfo = 0

[Present]
post $active = 0

; Shader ------------------------------

; Overrides ---------------------------

[TextureOverrideTravelerGirlPosition]
hash = 8239be13
run = CommandListTravelerGirlPosition
$active = 1

[TextureOverrideTravelerGirlBlend]
hash = 8772fa81
run = CommandListTravelerGirlBlend

[TextureOverrideTravelerGirlTexcoord]
hash = 8d2c7c7c
run = CommandListTravelerGirlTexcoord

[TextureOverrideTravelerGirlVertexLimitRaise]
hash = 0d8adebb

[TextureOverrideTravelerGirlIB]
hash = dfb54407
run = CommandListTravelerGirlIB

[TextureOverrideTravelerGirlHead]
hash = dfb54407
match_first_index = 0
run = CommandListTravelerGirlHead

[TextureOverrideTravelerGirlBody]
hash = dfb54407
match_first_index = 6915
run = CommandListTravelerGirlBody

[TextureOverrideTravelerGirlDress]
hash = dfb54407
match_first_index = 40413
run = CommandListTravelerGirlDress

[TextureOverrideTravelerGirlFaceHeadDiffuse]
hash = cdabcf6f
run = CommandListTravelerGirlFaceHeadDiffuse

[TextureOverride41FixVertexLimitRaise0]
hash = 846ff19c

; CommandList -------------------------

[CommandListTravelerGirlPosition]
if $swapvar == 0
	vb0 = ResourceTravelerGirlPosition.0
else if $swapvar == 1
	vb0 = ResourceTravelerGirlPosition.1
else if $swapvar == 2
	vb0 = ResourceTravelerGirlPosition.2
else if $swapvar == 3
	vb0 = ResourceTravelerGirlPosition.3
endif

[CommandListTravelerGirlBlend]
if $swapvar == 0
	vb1 = ResourceTravelerGirlBlend.0
	handling = skip
	draw = 14394,0
else if $swapvar == 1
	vb1 = ResourceTravelerGirlBlend.1
	handling = skip
	draw = 14485,0
else if $swapvar == 2
	vb1 = ResourceTravelerGirlBlend.2
	handling = skip
	draw = 14056,0
else if $swapvar == 3
	vb1 = ResourceTravelerGirlBlend.3
	handling = skip
	draw = 13887,0
endif

[CommandListTravelerGirlTexcoord]
if $swapvar == 0
	vb1 = ResourceTravelerGirlTexcoord.0
else if $swapvar == 1
	vb1 = ResourceTravelerGirlTexcoord.1
else if $swapvar == 2
	vb1 = ResourceTravelerGirlTexcoord.2
else if $swapvar == 3
	vb1 = ResourceTravelerGirlTexcoord.3
endif

[CommandListTravelerGirlIB]
if $swapvar == 0
	handling = skip
	drawindexed = auto
else if $swapvar == 1
	handling = skip
	drawindexed = auto
else if $swapvar == 2
	handling = skip
	drawindexed = auto
else if $swapvar == 3
	handling = skip
	drawindexed = auto
endif

[CommandListTravelerGirlHead]
if $swapvar == 0
	ib = ResourceTravelerGirlHeadIB.0
	ps-t0 = ResourceTravelerGirlHeadDiffuse.0
	ps-t1 = ResourceTravelerGirlHeadLightMap.0
else if $swapvar == 1
	ib = ResourceTravelerGirlHeadIB.1
	ps-t0 = ResourceTravelerGirlHeadDiffuse.1
	ps-t1 = ResourceTravelerGirlHeadLightMap.1
else if $swapvar == 2
	ib = ResourceTravelerGirlHeadIB.2
	ps-t0 = ResourceTravelerGirlHeadDiffuse.2
	ps-t1 = ResourceTravelerGirlHeadLightMap.2
else if $swapvar == 3
	ib = ResourceTravelerGirlHeadIB.3
	ps-t0 = ResourceTravelerGirlHeadDiffuse.3
	ps-t1 = ResourceTravelerGirlHeadLightMap.3
endif

[CommandListTravelerGirlBody]
if $swapvar == 0
	ib = ResourceTravelerGirlBodyIB.0
	ps-t0 = ResourceTravelerGirlBodyDiffuse.0
	ps-t1 = ResourceTravelerGirlBodyLightMap.0
else if $swapvar == 1
	ib = ResourceTravelerGirlBodyIB.1
	ps-t0 = ResourceTravelerGirlBodyDiffuse.1
	ps-t1 = ResourceTravelerGirlBodyLightMap.1
else if $swapvar == 2
	ib = ResourceTravelerGirlBodyIB.2
	ps-t0 = ResourceTravelerGirlBodyDiffuse.2
	ps-t1 = ResourceTravelerGirlBodyLightMap.2
else if $swapvar == 3
	ib = ResourceTravelerGirlBodyIB.3
	ps-t0 = ResourceTravelerGirlBodyDiffuse.3
	ps-t1 = ResourceTravelerGirlBodyLightMap.3
endif

[CommandListTravelerGirlDress]
if $swapvar == 0
	ib = ResourceTravelerGirlDressIB.0
	ps-t0 = ResourceTravelerGirlDressDiffuse.0
	ps-t1 = ResourceTravelerGirlDressLightMap.0
else if $swapvar == 1
	ib = ResourceTravelerGirlDressIB.1
	ps-t0 = ResourceTravelerGirlDressDiffuse.1
	ps-t1 = ResourceTravelerGirlDressLightMap.1
else if $swapvar == 2
	ib = null
	ps-t0 = ResourceTravelerGirlDressDiffuse.2
	ps-t1 = ResourceTravelerGirlDressLightMap.2
else if $swapvar == 3
	ib = null
	ps-t0 = ResourceTravelerGirlDressDiffuse.3
	ps-t1 = ResourceTravelerGirlDressLightMap.3
endif

[CommandListTravelerGirlFaceHeadDiffuse]
if $swapvar == 0
	ps-t0 = ResourceTravelerGirlFaceHeadDiffuse.0
else if $swapvar == 1
	ps-t0 = ResourceTravelerGirlFaceHeadDiffuse.1
else if $swapvar == 2
	ps-t0 = ResourceTravelerGirlFaceHeadDiffuse.2
else if $swapvar == 3
	ps-t0 = ResourceTravelerGirlFaceHeadDiffuse.3
endif

; Resources ---------------------------

[ResourceTravelerGirlPosition.0]
type = Buffer
stride = 40
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlPosition.buf

[ResourceTravelerGirlBlend.0]
type = Buffer
stride = 32
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlBlend.buf

[ResourceTravelerGirlTexcoord.0]
type = Buffer
stride = 20
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlTexcoord.buf

[ResourceTravelerGirlHeadIB.0]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlHead.ib

[ResourceTravelerGirlBodyIB.0]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlBody.ib

[ResourceTravelerGirlDressIB.0]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlDress.ib

[ResourceTravelerGirlHeadDiffuse.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlHeadDiffuse.dds

[ResourceTravelerGirlHeadLightMap.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlHeadLightMap.dds

[ResourceTravelerGirlBodyDiffuse.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlBodyDiffuse.dds

[ResourceTravelerGirlBodyLightMap.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlBodyLightMap.dds

[ResourceTravelerGirlDressDiffuse.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlDressLightMap.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlDressLightMap.dds

[ResourceTravelerGirlFaceHeadDiffuse.0]
filename = .\0 - Dress\TravelerGirlMod\TravelerGirlFaceHeadDiffuse.dds

[ResourceTravelerGirlPosition.1]
type = Buffer
stride = 40
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlPosition.buf

[ResourceTravelerGirlBlend.1]
type = Buffer
stride = 32
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlBlend.buf

[ResourceTravelerGirlTexcoord.1]
type = Buffer
stride = 20
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlTexcoord.buf

[ResourceTravelerGirlHeadIB.1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlHead.ib

[ResourceTravelerGirlBodyIB.1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlBody.ib

[ResourceTravelerGirlDressIB.1]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlDress.ib

[ResourceTravelerGirlHeadDiffuse.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlHeadDiffuse.dds

[ResourceTravelerGirlHeadLightMap.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlHeadLightMap.dds

[ResourceTravelerGirlBodyDiffuse.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlBodyDiffuse.dds

[ResourceTravelerGirlBodyLightMap.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlBodyLightMap.dds

[ResourceTravelerGirlDressDiffuse.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlDressLightMap.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlDressLightMap.dds

[ResourceTravelerGirlFaceHeadDiffuse.1]
filename = .\1 - Dress no Top\TravelerGirlMod\TravelerGirlFaceHeadDiffuse.dds

[ResourceTravelerGirlPosition.2]
type = Buffer
stride = 40
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlPosition.buf

[ResourceTravelerGirlBlend.2]
type = Buffer
stride = 32
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlBlend.buf

[ResourceTravelerGirlTexcoord.2]
type = Buffer
stride = 20
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlTexcoord.buf

[ResourceTravelerGirlHeadIB.2]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlHead.ib

[ResourceTravelerGirlBodyIB.2]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlBody.ib

[ResourceTravelerGirlDressIB.2]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlDress.ib

[ResourceTravelerGirlHeadDiffuse.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlHeadDiffuse.dds

[ResourceTravelerGirlHeadLightMap.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlHeadLightMap.dds

[ResourceTravelerGirlBodyDiffuse.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlBodyDiffuse.dds

[ResourceTravelerGirlBodyLightMap.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlBodyLightMap.dds

[ResourceTravelerGirlDressDiffuse.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlDressLightMap.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlDressLightMap.dds

[ResourceTravelerGirlFaceHeadDiffuse.2]
filename = .\2 - No Dress no Top\TravelerGirlMod\TravelerGirlFaceHeadDiffuse.dds

[ResourceTravelerGirlPosition.3]
type = Buffer
stride = 40
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlPosition.buf

[ResourceTravelerGirlBlend.3]
type = Buffer
stride = 32
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlBlend.buf

[ResourceTravelerGirlTexcoord.3]
type = Buffer
stride = 20
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlTexcoord.buf

[ResourceTravelerGirlHeadIB.3]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlHead.ib

[ResourceTravelerGirlBodyIB.3]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlBody.ib

[ResourceTravelerGirlDressIB.3]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlDress.ib

[ResourceTravelerGirlHeadDiffuse.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlHeadDiffuse.dds

[ResourceTravelerGirlHeadLightMap.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlHeadLightMap.dds

[ResourceTravelerGirlBodyDiffuse.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlBodyDiffuse.dds

[ResourceTravelerGirlBodyLightMap.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlBodyLightMap.dds

[ResourceTravelerGirlDressDiffuse.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlDressDiffuse.dds

[ResourceTravelerGirlDressLightMap.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlDressLightMap.dds

[ResourceTravelerGirlFaceHeadDiffuse.3]
filename = .\3 - No Dress\TravelerGirlMod\TravelerGirlFaceHeadDiffuse.dds



; .ini generated by GIMI (Genshin-Impact-Model-Importer) mod merger script
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord